-- https://school.programmers.co.kr/learn/courses/30/lessons/59043 
SELECT O.ANIMAL_ID,	O.NAME
FROM ANIMAL_OUTS AS O JOIN ANIMAL_INS AS I 
ON O.ANIMAL_ID = I.ANIMAL_ID
WHERE I.DATETIME > O.DATETIME
ORDER BY I.DATETIME;