-- https://school.programmers.co.kr/learn/courses/30/lessons/144856
SELECT a.AUTHOR_ID	,a.AUTHOR_NAME,	b.CATEGORY  , SUM((SALES * PRICE)) AS TOTAL_SALES
FROM AUTHOR A JOIN BOOK B ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID , b.CATEGORY DESC


