-- https://school.programmers.co.kr/learn/courses/30/lessons/133026

SELECT INGREDIENT_TYPE	, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO I
INNER JOIN FIRST_HALF F ON I.FLAVOR = F.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER 