-- https://school.programmers.co.kr/learn/courses/30/lessons/131114
SELECT WAREHOUSE_ID, WAREHOUSE_NAME, ADDRESS,
    CASE WHEN FREEZER_YN IS NULL THEN "N"
    ELSE FREEZER_YN END AS FR
FROM FOOD_WAREHOUSE
WHERE ADDRESS LIKE "경기도 %" 