-- https://school.programmers.co.kr/learn/courses/30/lessons/131115
-- SOLUTION1
SELECT * FROM FOOD_PRODUCT
ORDER BY PRICE DESC
LIMIT 1;

-- SOLUTION2
SELECT * FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);